### ISSUE TITLE
Show icon in the main toolbar instead of under the dropdown

### ISSUE THREAD

**Issue by mchubby** [multidots/multicollab#17]
Hi,
I'm not using the plugin (or Wordpress) but you might be interested in moving the button to a more accessible place in the editor toolbar, using `BlockControls` instead of `RichTextToolbarButton`.

See in particular the commit referenced at https://github.com/WordPress/gutenberg/issues/14881#issuecomment-624611260

**Comment by poojabhimani12** [comment]
Hello Mchubby,

Thanks for your valuable Feedback. Luckily we both are on the same page and our team is already working on this. We are going to release this feature in our next release.

Feel Free to contact us if any new suggestions in your mind.

Thnaks,
Pooja
