### ISSUE TITLE
class-commenting-block-public.php: enqueues assets with double slash, causes redirects

### ISSUE THREAD

**Issue by lkraav** [multidots/multicollab#37]
https://developer.wordpress.org/reference/functions/plugin_dir_url/ uses `trailingslashit()`.

https://github.com/multidots/multicollab/blob/23b1633680e00e15bedf69a801d009ccdf9d6016/public/class-commenting-block-public.php#L80

and

https://github.com/multidots/multicollab/blob/23b1633680e00e15bedf69a801d009ccdf9d6016/public/class-commenting-block-public.php#L103

should not add another  slash behind `COMMENTING_BLOCK_URL`.

URL cleanse redirect like below will trip on this mistake

```
# BEGIN Eliminate double slashes
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{THE_REQUEST} //
  RewriteRule ^.*$ $0 [R=302,L,NE]
</IfModule>
# END Eliminate double slashes
```

Source: https://stackoverflow.com/q/31933042/35946

**Comment by lkraav** [comment]
Also, I looked into these files, and they carry nothing meaningful.

Can we just stop enqueuing them and causing page speed measurement issues for no reason?

**Comment by poojabhimani12** [comment]
Yes Ikraav , We can stop enqueuing them. You can create pull request for this.
