### ISSUE TITLE
Multicolab breaks when used with plugin HTML Editor Syntax Highlighter

### ISSUE THREAD

**Issue by supermario12342003** [multidots/multicollab#45]
Hi,

I encounter error when i view the content as code with the plugin `HTML Editor Syntax Highlighter`.

After viewing as code and change back to normal view, upon clicking the save button, i encounter an error, and i think it's related to your plugin.
<img width="619" alt="Screenshot 2022-01-21 at 14 48 44" src="https://user-images.githubusercontent.com/6221160/150538061-a3aee0ad-a0e1-4d06-ad43-8dc40ff8814a.png">
<img width="419" alt="Screenshot 2022-01-21 at 14 48 57" src="https://user-images.githubusercontent.com/6221160/150538086-2750ac8f-c1a6-499b-882d-cbe4e368a3c1.png">

**Comment by poojabhimani12** [comment]
Hello @supermario12342003 ,

Our team could not regenerate this issue with the latest Multicollab build. Are you using the latest version of Multicollab? Which WordPress Version are you using? Can you please provide us with more details?

**Comment by supermario12342003** [comment]
Hi @poojabhimani12 ,

The versions i have are :
Wordpress: 5.8.1
Multicollab: 2.0.2
HTML Editor Syntax Highlighter: 2.4.4

The problem does not exist if i just use the Multicollab and view the content with the default Code Editor provided by Wordpress.

**Comment by supermario12342003** [comment]
Hi @poojabhimani12, 

I see the issue has been closed, did you manage to reproduce and fix the bug?

**Comment by poojabhimani12** [comment]
Yes,  In the next release, it will be fixed.

**Comment by supermario12342003** [comment]
Thanks :)
