### ISSUE TITLE
Incorrectly comparing isset() against strings

### ISSUE THREAD

**Issue by GaryJones** [multidots/multicollab#54]
https://github.com/multidots/multicollab/blob/f45518ace0ae089f00997ff49d74f5ec814c0de3/admin/classes/class-commenting-block-rest-routes.php#L130

Since PHP's [`isset()` function](https://www.php.net/manual/en/function.isset.php) will return boolean `true` or `false`, then it's never going to match any particular string; this conditional is fundamentally flawed.

**Comment by poojabhimani12** [comment]
Gray, Thanks for your valuable feedback. We will cover this in our next upcoming release.

**Comment by poojabhimani12** [comment]
Gray, We have covered the above suggestion in the latest version, 3.3.

**Comment by GaryJones** [comment]
@poojabhimani12 Looking at the tag for V3.3, https://github.com/multidots/multicollab/blob/627090ed9ca35e3f597c1185746c806964c41445/admin/classes/class-commenting-block-rest-routes.php#L130 shows no changes.

**Comment by poojabhimani12** [comment]
I apologize Gray, you can check [here](https://github.com/multidots/multicollab/commit/57a6d6bd437257804785a488c0c8255d55f46359) the changes
