### ISSUE TITLE
Breaks all non-WP Gutenberg blocks

### ISSUE THREAD

**Issue by peter-thepodcasthost** [multidots/multicollab#63]
The latest version of the plugin (3.7) breaks all non-WP Gutenberg blocks. Attaching a video recreation below:

https://share.cleanshot.com/DK2MT573ww1fjGPPBH0G

Everything works fine on version 3.6. Please let me know if I can do anything to help out 👍

**Comment by poojabhimani12** [comment]
Peter - please update the plugin with the latest version and check.
